from flask import Flask, render_template, request, redirect, url_for, session, flash
from werkzeug.security import generate_password_hash, check_password_hash
import sqlite3
import os

app = Flask(__name__)
app.secret_key = 'your_secret_key_here'  # Change this to a random string for security

# Database setup
DATABASE = 'students.db'

def get_db():
    db = sqlite3.connect(DATABASE)
        db.row_factory = sqlite3.Row
            return db

            def init_db():
                with app.app_context():
                        db = get_db()
                                db.execute('''CREATE TABLE IF NOT EXISTS students (
                                                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                                                                                username TEXT UNIQUE NOT NULL,
                                                                                                        email TEXT UNIQUE NOT NULL,
                                                                                                                                password TEXT NOT NULL
                                                                                                                                                     )''')
                                                                                                                                                             db.commit()

                                                                                                                                                             init_db()  # Initialize the database on startup

                                                                                                                                                             @app.route('/')
                                                                                                                                                             def home():
                                                                                                                                                                 if 'username' in session:
                                                                                                                                                                         return f"Welcome, {session['username']}! <a href='/logout'>Logout</a>"
                                                                                                                                                                             return redirect(url_for('login'))

                                                                                                                                                                             @app.route('/register', methods=['GET', 'POST'])
                                                                                                                                                                             def register():
                                                                                                                                                                                 if request.method == 'POST':
                                                                                                                                                                                         username = request.form['username']
                                                                                                                                                                                                 email = request.form['email']
                                                                                                                                                                                                         password = generate_password_hash(request.form['password'])
                                                                                                                                                                                                                 
                                                                                                                                                                                                                         db = get_db()
                                                                                                                                                                                                                                 try:
                                                                                                                                                                                                                                             db.execute('INSERT INTO students (username, email, password) VALUES (?, ?, ?)',
                                                                                                                                                                                                                                                                    (username, email, password))
                                                                                                                                                                                                                                                                                db.commit()
                                                                                                                                                                                                                                                                                            flash('Registration successful! Please log in.')
                                                                                                                                                                                                                                                                                                        return redirect(url_for('login'))
                                                                                                                                                                                                                                                                                                                except sqlite3.IntegrityError:
                                                                                                                                                                                                                                                                                                                            flash('Username or email already exists.')
                                                                                                                                                                                                                                                                                                                                    finally:
                                                                                                                                                                                                                                                                                                                                                db.close()
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                        return render_template('register.html')

                                                                                                                                                                                                                                                                                                                                                        @app.route('/login', methods=['GET', 'POST'])
                                                                                                                                                                                                                                                                                                                                                        def login():
                                                                                                                                                                                                                                                                                                                                                            if request.method == 'POST':
                                                                                                                                                                                                                                                                                                                                                                    username = request.form['username']
                                                                                                                                                                                                                                                                                                                                                                            password = request.form['password']
                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                            db = get_db()
                                                                                                                                                                                                                                                                                                                                                                                                    user = db.execute('SELECT * FROM students WHERE username = ?', (username,)).fetchone()
                                                                                                                                                                                                                                                                                                                                                                                                            db.close()
                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                            if user and check_password_hash(user['password'], password):
                                                                                                                                                                                                                                                                                                                                                                                                                                        session['username'] = user['username']
                                                                                                                                                                                                                                                                                                                                                                                                                                                    return redirect(url_for('home'))
                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        flash('Invalid username or password.')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return render_template('login.html')

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                @app.route('/logout')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def logout():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    session.pop('username', None)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return redirect(url_for('login'))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if __name__ == '__main__':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            app.run(debug=True)from flask import Flask, render_template, request, redirect, url_for, session, flash
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            from werkzeug.security import generate_password_hash, check_password_hash
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            import sqlite3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            import os

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            app = Flask(__name__)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            app.secret_key = 'your_secret_key_here'  # Change this to a random string for security

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Database setup
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            DATABASE = 'students.db'

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def get_db():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                db = sqlite3.connect(DATABASE)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    db.row_factory = sqlite3.Row
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return db

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def init_db():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            with app.app_context():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    db = get_db()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            db.execute('''CREATE TABLE IF NOT EXISTS students (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            username TEXT UNIQUE NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    email TEXT UNIQUE NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            password TEXT NOT NULL
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 )''')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         db.commit()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         init_db()  # Initialize the database on startup

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         @app.route('/')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         def home():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if 'username' in session:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return f"Welcome, {session['username']}! <a href='/logout'>Logout</a>"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return redirect(url_for('login'))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         @app.route('/register', methods=['GET', 'POST'])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         def register():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if request.method == 'POST':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     username = request.form['username']
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             email = request.form['email']
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     password = generate_password_hash(request.form['password'])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     db = get_db()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         db.execute('INSERT INTO students (username, email, password) VALUES (?, ?, ?)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                (username, email, password))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            db.commit()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        flash('Registration successful! Please log in.')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return redirect(url_for('login'))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            except sqlite3.IntegrityError:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        flash('Username or email already exists.')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                finally:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            db.close()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return render_template('register.html')

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @app.route('/login', methods=['GET', 'POST'])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def login():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if request.method == 'POST':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                username = request.form['username']
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        password = request.form['password']
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        db = get_db()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                user = db.execute('SELECT * FROM students WHERE username = ?', (username,)).fetchone()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        db.close()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if user and check_password_hash(user['password'], password):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    session['username'] = user['username']
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return redirect(url_for('home'))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    flash('Invalid username or password.')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return render_template('login.html')

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @app.route('/logout')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def logout():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                session.pop('username', None)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return redirect(url_for('login'))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if __name__ == '__main__':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.run(debug=True)